### ISSUE TITLE
Add support for tf.nn.l2_normalize

### ISSUE THREAD

**Issue by Alnlll** [kendryte/kendryte-model-compiler#55]
**Question**
Got an error when I was trying converting a model with output(result from tf.nn.l2_normalize) like:
```bash
Traceback (most recent call last):
  File "__main__.py", line 143, in <module>
    main()
  File "__main__.py", line 116, in main
    k210_layers = model_loader_module.load_model(dataset_val, rfb, args)
  File "/home/**/work/007_npu/001_k210/kendryte-model-compiler/model_loader/pb/__init__.py", line 65, in load_model
    converter.convert()
  File "/home/**/work/007_npu/001_k210/kendryte-model-compiler/model_loader/pb/tensor_head_to_tensor_list.py", line 220, in convert
    while self.convert_step():
  File "/home/**/work/007_npu/001_k210/kendryte-model-compiler/model_loader/pb/tensor_head_to_tensor_list.py", line 215, in convert_step
    raise ValueError('no converter for', self.output_tensor.op.type, 'name:', self.output_tensor.op.name)
ValueError: ('no converter for', 'Mul', 'name:', 'embeddings')
```

converting commands:
```
python3 __main__.py --pb_path mobilenet_v2.pb --tensor_output_name embeddings --dataset_input_name input:0  --image_w 160 --image_h 160
```

**Comment by noah-lcf** [comment]
tried mobilenet-v2 and inception,got the same **'no converter for'** error.

**Comment by silentneuron** [comment]
I am trying with mobilenet_v2 as well. Based on my understanding, some layer combinations in mobilenet_v2 are not defined in [`ty_match`](https://github.com/kendryte/kendryte-model-compiler/blob/master/model_loader/pb/tensor_head_to_tensor_list.py#L79).
