### ISSUE TITLE
KeyError: 'yolo'

### ISSUE THREAD

**Issue by nmk456** [kendryte/kendryte-model-compiler#73]
I'm trying to convert a custom trained darknet tiny-yolo model to use on the K210, but I'm getting an error:

    Traceback (most recent call last):
      File "__main__.py", line 150, in <module>
        main()
      File "__main__.py", line 123, in main
        k210_layers = model_loader_module.load_model(dataset_val, rfb, args)
      File "C:\Users\Nathan\kendryte-model-compiler\model_loader\darknet\__init__.py", line 87, in load_model
        decode_darknet(cfg_path, weights_path, build_dir)
      File "C:\Users\Nathan\kendryte-model-compiler\model_loader\darknet\__init__.py", line 28, in decode_darknet
        dtype='float32')
      File "C:\Users\Nathan\kendryte-model-compiler\model_loader\darknet\D2T_lib\darknet_tool.py", line 67, in __init__
        self.from_cfg_file(cfg_file)
      File "C:\Users\Nathan\kendryte-model-compiler\model_loader\darknet\D2T_lib\darknet_tool.py", line 75, in from_cfg_file
        self.net.layers_from_cfg(cfg_file)
      File "C:\Users\Nathan\kendryte-model-compiler\model_loader\darknet\D2T_lib\net.py", line 68, in layers_from_cfg
        self.parse_block(contents[block_st:line_id], copy.copy(block_id))
      File "C:\Users\Nathan\kendryte-model-compiler\model_loader\darknet\D2T_lib\net.py", line 118, in parse_block
        initializer = __parse_layers__[default_name]
        KeyError: 'yolo'

The command I'm using to run it is:
`python __main__.py --model_loader model_loader/darknet --cfg_path darknet/yolo-tiny.cfg --weights_path darknet/yolo-tiny.weights`

The weights and config are modified and trained with darknet.

**Comment by nmk456** [comment]
I looked at the darknet configs for tiny yolo that I used, and it looks like there are some changes between v2 and v3 of yolo-tiny that change some things that cause this error. Could it be updated to support yolo-tinyv3? Here's the config: https://github.com/pjreddie/darknet/blob/master/cfg/yolov3-tiny.cfg
